#feign:
#  hystrix:
#    enabled: true
dubbo:
  application:
    id: dubbo-sca-provider
    name: dubbo-sca-provider
    qos-enable: false
#    qos-port: 33333
#    qos:
#     enable: false
#     port: 33333
#     accept:
#       foreign:
#         ip: false
  registry:
    address: spring-cloud://localhost
#    address: zookeeper://192.168.56.101:2181
  protocol:
    name: dubbo
    port: -1
#  config:
#    multiple: true
#  protocols:
#    dubbo:
#      name: dubbo
#      port: -1
#    rest:
#      name: rest
#      port: 8081
#      server: netty

