#server:
#  port: 0
dubbo:
  application:
    id: dubbo-sca-consumer
    name: dubbo-sca-consumer
    qos-enable: false
  registry:
    address: spring-cloud://localhost
  consumer:
    check: false
  cloud:
    subscribed-services: dubbo-sca-provider
#provider:
#  application:
#    name: dubbo-sca-provider
spring:
  cloud:
    service-registry:
      auto-registration:
        # 要禁用这个，否则需要web环境才能启动
        enabled: false
