spring:
  application:
    name: dubbo-provider-2.7.x
dubbo:
  scan:
    base-packages: top.ylonline.dubbo27x
  application:
    name: ${spring.application.name}
    qos-enable: false
  registry:
    address: zookeeper://192.168.56.101:2181
    client: curator
    simplified: true
  metadata-report:
    address: ${dubbo.registry.address}
#  protocol:
#    name: dubbo
#    port: -1
#    server: netty
#  protocol:
#    name: rest
#    port: 9090
#    server: netty
  config:
    multiple: true
  protocols:
    dubbo:
      name: dubbo
      port: -1
      server: netty
    rest:
      name: rest
      port: 9090
      server: netty
  provider:
    delay: -1
    timeout: 20000
    retries: 0